# Generated by Django 3.2.5 on 2021-07-26 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan_text', models.CharField(max_length=5000)),
                ('votes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertanyaans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pertanyaan',
            },
        ),
        migrations.CreateModel(
            name='Komen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komen_text', models.CharField(max_length=5000)),
                ('votes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komens', to='faq.pertanyaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'komen',
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageuploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imageupload',
            },
        ),
    ]
