# Generated by Django 3.2.5 on 2021-07-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='uploaded_at',
            new_name='pub_date',
        ),
    ]
